apiVersion: v1
kind: Service
metadata:
  name: saga-orchestrator
  namespace: ticketing-system
  labels:
    app: saga-orchestrator
spec:
  type: ClusterIP
  selector:
    app: saga-orchestrator
  ports:
  - name: http
    port: 8086
    targetPort: 8086
    protocol: TCP
